# Generated by Django 3.0.3 on 2020-09-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petroleum_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
    ]
