# Generated by Django 3.0.3 on 2020-09-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petroleum_report', '0002_auto_20200909_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
