# Generated by Django 3.1.1 on 2020-09-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petroleum_report', '0003_auto_20200909_1018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Year',
            new_name='YearBarsa',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='year_sales',
            new_name='YearBarsa_sales',
        ),
        migrations.RenameField(
            model_name='yearbarsa',
            old_name='year',
            new_name='year_barsa',
        ),
    ]
