# Generated by Django 3.1.1 on 2020-09-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petroleum_report', '0004_auto_20200912_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='YearBarsa_sales',
            new_name='year_sales',
        ),
    ]
